# Generated by Django 5.2.4 on 2025-07-21 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funATIAPP', '0003_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to='funATIAPP.profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friends_with', to='funATIAPP.profile'),
        ),
    ]
