# Generated by Django 5.2.3 on 2025-07-22 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funATIAPP', '0005_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='chat_media/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
