# Generated by Django 5.2.3 on 2025-07-23 00:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funATIAPP', '0007_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privacy', models.CharField(choices=[('privado', 'Privado'), ('publico', 'Público'), ('solo_amigos', 'Solo amigos')], default='publico', max_length=20)),
                ('language', models.CharField(choices=[('es', 'Español'), ('en', 'English'), ('fr', 'Français')], default='es', max_length=10)),
                ('color_theme', models.CharField(choices=[('rosado', 'Rosado'), ('azul', 'Azul'), ('verde', 'Verde')], default='rosado', max_length=20)),
                ('theme_mode', models.CharField(choices=[('claro', 'Modo Claro'), ('oscuro', 'Modo Oscuro'), ('automatico', 'Automático')], default='claro', max_length=20)),
                ('email_notifications', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
