# Generated by Django 5.2.3 on 2025-07-23 11:47

from django.db import migrations


def update_privacy_settings(apps, schema_editor):
    """
    Migrar los valores de privacidad:
    - 'solo_amigos' -> 'privado' (nuevo comportamiento: solo amigos pueden ver)
    - 'privado' -> 'privado' (mantener, pero ahora significa solo amigos)
    - 'publico' -> 'publico' (sin cambios)
    """
    UserSettings = apps.get_model('funATIAPP', 'UserSettings')
    
    # Actualizar todos los usuarios que tenían 'solo_amigos' a 'privado'
    UserSettings.objects.filter(privacy='solo_amigos').update(privacy='privado')
    
    # Los que tenían 'privado' ya se quedan como 'privado' 
    # (aunque el comportamiento cambia: antes nadie podía ver, ahora solo amigos)
    
    # Los que tenían 'publico' se mantienen igual


def reverse_privacy_settings(apps, schema_editor):
    """
    Función de reversión (no es necesaria en este caso específico)
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('funATIAPP', '0009_usersettings_created_at'),
    ]

    operations = [
        migrations.RunPython(update_privacy_settings, reverse_privacy_settings),
    ]
