# Generated by Django 5.2.3 on 2025-07-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funATIAPP', '0010_auto_20250723_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='privacy',
            field=models.CharField(choices=[('publico', 'Público'), ('privado', 'Privado')], default='publico', max_length=20),
        ),
    ]
