name: atigrupo2

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Set up Docker
        run: |
          # Add Docker's official GPG key
          sudo apt-get update
          sudo apt-get install -y ca-certificates curl gnupg
          sudo install -m 0755 -d /etc/apt/keyrings
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
          sudo chmod a+r /etc/apt/keyrings/docker.gpg

          # Add the repository to Apt sources
          echo \
            "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
            $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
            sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

          # Install Docker packages
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

          # Install Docker Compose
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

          # Verify installation
          docker --version
          docker-compose --version

      - name: Build and run Docker Compose
        run: |
          docker-compose build
          docker-compose up -d
          # Wait for Apache to start
          sleep 10

      - name: Check Apache status
        run: |
          docker-compose ps
          docker-compose exec -T web apache2ctl -S

      - name: Run Django migrations
        run: |
          docker-compose exec -T web python3 /app/funATI/manage.py migrate --noinput

      - name: Run Django tests
        run: |
          docker-compose exec -T web python3 /app/funATI/manage.py test

      - name: Shut down Docker containers
        run: |
          docker-compose down